### ISSUE TITLE
autoFlush_ is used uninitialized

### ISSUE THREAD

**Issue by snej** [rudi-cilibrasi/zlibcomplete#5]
In zlibtop.cpp, the member `autoFlush_` is never initialized, and has no setter, but is used in the `baseCompress` method.

I discovered this because `baseCompress` was sometimes failing for no reason; it turns out this happened whenever `autoFlush_` randomly had a nonzero value. For some reason this causes the call to `deflate` to fail.

I fixed the bug by adding a line to the constructor that sets `autoFlush = false`, but it seems that this variable could be removed entirely since there's no way to ever set it to true.

**Comment by rudi-cilibrasi** [comment]
Thanks for this bug report.  The intention was for the optional autoflush parameter passed into the constructors to be used.  I have since corrected this problem in the PR and branch https://github.com/rudi-cilibrasi/zlibcomplete/pull/6    Can you let me know if you are able to give this branch a try before I merge it into master?

**Comment by rudi-cilibrasi** [comment]
@snej Did you manage to give it a try?

**Comment by snej** [comment]
Yup, it fixes the problem for me. Thanks!

**Comment by rudi-cilibrasi** [comment]
you're welcome! :+1:
